name: web_buttons
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/djcali570/web_buttons

environment:
  sdk: ">=2.16.0-144.0.dev <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: WebButtonIcons
      fonts:
        - asset: lib/src/fonts/WebButtonIcons.ttf
