name: flutter_web_buttons
description: Add fully customizable animated buttons or icon buttons easily to your web project.
version: 0.0.7
maintainer: J.Cali (@djcali570)
homepage: https://github.com/djcali570/flutter_web_buttons

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  fonts:
    - family: WebButtonSocialIcons
      fonts:
        - asset: lib/fonts/WebButtonSocialIcons.ttf
