enum FlutterWebButtonList {
  backgroundColorChange,
  backgroundFill,
  buttonGrow,
  iconGrow,
  raiseText,
  simple,
  socialIcon,
  socialIconGrow,
  textColorChange,
  textScroll,
}

enum FlutterWebButtonSocialIcon {
  facebook,
  facebookSquare,
  flickr,
  github,
  githubSquare,
  instagram,
  instagramSquare,
  linkedin,
  linkedinSquare,
  paypal,
  paypalSquare,
  pinterest,
  pinterestSquare,
  snapchat,
  snapchatSquare,
  soundcloud,
  twitter,
  twittersquare,
  vimeo,
  vimeoSquare,
  youtube,
  youtubeSquare,
}
